Add helm chart apps
Signed-off-by: jagyugyaerik <jagyugyaerik@gmail.com>

diff --git a/charts/visualization/templates/deployment.yaml b/charts/visualization/templates/deployment.yaml
--- a/charts/visualization/templates/deployment.yaml
+++ b/charts/visualization/templates/deployment.yaml
@@ -27,6 +27,54 @@ spec:
       serviceAccountName: {{ include "visualization.serviceAccountName" . }}
       securityContext:
         {{- toYaml .Values.podSecurityContext | nindent 8 }}
+      initContainers:
+        {{- if .Values.redisWait.enabled }}
+        - name: wait-for-redis
+          image: {{ include "common.images.image" (dict "imageRoot" .Values.redis.image "global" .Values.global) }}
+          imagePullPolicy: {{ .Values.redis.image.pullPolicy | quote }}
+          {{- with .Values.redisWait.securityContext }}
+          securityContext: {{ . | toYaml }}
+          {{- end }}
+          command:
+            - /bin/bash
+          args:
+            - -ec
+            - |
+                #!/bin/bash
+                set -o errexit
+                set -o nounset
+                set -o pipefail
+                . /opt/bitnami/scripts/libos.sh
+                . /opt/bitnami/scripts/liblog.sh
+                check_redis_connection() {
+                  local result="$(redis-cli -h {{ include "visualization.redisHost" . }} -p {{ include "visualization.redisPort" . }} {{ .Values.redisWait.extraArgs }} PING)"
+                  if [[ "$result" != "PONG" ]]; then
+                    false
+                  fi
+                }
+                info "Checking redis connection..."
+                if ! retry_while "check_redis_connection"; then
+                    error "Could not connect to the Redis server"
+                    return 1
+                else
+                    info "Connected to the Redis instance"
+                fi
+          {{- if include "visualization.redis.auth.enabled" . }}
+          env:
+            - name: REDISCLI_AUTH
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "visualization.redis.secretName" . }}
+                  key: {{ include "visualization.redis.secretPasswordKey" . }}
+          {{- end }}
+          {{- end }}
+          {{- if and .Values.redis.enabled (include "visualization.redis.auth.enabled" .) }}
+            - name: REDIS_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "visualization.redis.secretName" . }}
+                  key: {{ include "visualization.redis.secretPasswordKey" . }}
+          {{- end }}
       containers:
         - name: {{ .Chart.Name }}
           securityContext:
@@ -35,16 +83,61 @@ spec:
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           ports:
             - name: http
-              containerPort: 80
+              containerPort: {{ .Values.service.containerPort }}
               protocol: TCP
-          livenessProbe:
-            httpGet:
-              path: /
-              port: http
-          readinessProbe:
-            httpGet:
-              path: /
-              port: http
+          env:
+            - name: REDIS_HOST
+              value: {{ include "visualization.redisHost" . }}
+            - name: REDIS_PORT
+              value: {{ include "visualization.redisPort" . }}
+            {{- if and (not .Values.externalRedis.password) (include "visualization.redis.auth.enabled" .) }}
+            - name: REDIS_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "visualization.redis.secretName" . }}
+                  key: {{ include "visualization.redis.secretPasswordKey" . }}
+            {{- else }}
+            - name: REDIS_PASSWORD
+              value: {{ .Values.externalRedis.password }}
+            {{- end }}
+            - name: APP_DEV_PORT
+              value: {{ .Values.app.dev.port | quote }}
+            - name: APP_DEV_PROCESSES
+              value: {{ .Values.app.dev.processes | quote }}
+            - name: APP_DEV_WATCH_INTERVAL
+              value: {{ .Values.app.dev.watchInterval | quote }}
+            - name: APP_HOST_PORT
+              value: {{ .Values.app.hostPort | quote }}
+            - name: APP_TITLE
+              value: {{ .Values.app.title | quote }}
+            - name: STORAGE_BASE_URL
+              value: {{ .Values.app.storage.baseURL | quote }}
+            - name: STORAGE_DATA_BUCKET
+              value: {{ .Values.app.storage.dataBucket | quote }}
+            {{- if .Values.extraEnvVars }}
+            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
+            {{- end }}
+          envFrom:
+            {{- if .Values.extraEnvVarsCM }}
+            - configMapRef:
+                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsCM "context" $) }}
+            {{- end }}
+            {{- if .Values.extraEnvVarsSecret }}
+            - secretRef:
+                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsSecret "context" $) }}
+            {{- end }}
+          {{- if .Values.extraVolumeMounts }}
+          volumeMounts:
+          {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
+          {{- end }}
+          # livenessProbe:
+          #   httpGet:
+          #     path: /
+          #     port: http
+          # readinessProbe:
+          #   httpGet:
+          #     path: /
+          #     port: http
           resources:
             {{- toYaml .Values.resources | nindent 12 }}
       {{- with .Values.nodeSelector }}
@@ -58,4 +151,8 @@ spec:
       {{- with .Values.tolerations }}
       tolerations:
         {{- toYaml . | nindent 8 }}
+      {{- end }}
+      {{- if .Values.extraVolumes }}
+      volumes:
+      {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
       {{- end }}
